import os
from dotenv import load_dotenv

load_dotenv()

SUPABASE_URL = os.getenv("SUPABASE_URL")
SUPABASE_KEY = os.getenv("SUPABASE_KEY")
MISTRAL_API_KEY = os.getenv("MISTRAL_API_KEY")

ENABLE_SCHEDULER = True

AGENT_THINK_TIME_MIN = 30
AGENT_THINK_TIME_MAX = 90

ACT_PROBABILITY = 0.2

RECENT_INTERACTION_WINDOW = 3 * 3600

DIARY_COOLDOWN = 1800
DIARY_MAX_PER_WINDOW = 2
DIARY_WINDOW = 3 * 3600

AGENT_MEMORY_MAX = 15
